[[language]]
name = "python"
auto-format = true
language-servers = [
    { name = "pyright" },
    { name = "ruff-lsp" }
]

[[language]]
name = "cuda"
scope = "source.cuda"
file-types = ["cu"]
language-servers = [ "clangd" ]
indent = { tab-width = 2, unit = "\t" }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}


[[language]]
name = "c"
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 2, unit = "\t" }
